services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env   # 👈 NEW: load everything from .env

  worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env   # 👈 NEW: load everything from .env