services:
  # Main Flask application
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    networks:
      - diffsage-network

  # CloudRun task service
  task-service:
    build: ./cloudrun_task_service
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./cloudrun_task_service:/app
    networks:
      - diffsage-network

  # Redis for rate limiting and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - diffsage-network

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: diffsage
      POSTGRES_USER: diffsage
      POSTGRES_PASSWORD: diffsage_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - diffsage-network

volumes:
  redis_data:
  postgres_data:

networks:
  diffsage-network:
    driver: bridge
